### ISSUE TITLE
Get rid of manage.py loaddata and replace with migrations

### ISSUE THREAD

**Issue by Gasoid** [ilyinon/tt_django#1]
Steps:
1) waiting a postgres start
2) manage.py migrate
3) run server (gunicorn)

**Comment by ilyinon** [comment]
For answering first question which is located in  heading of this issue,
I deleted loaddata and merge it to migration scripts. it was implemented in commit ```https://github.com/ilyinon/tt_django/commit/3a6eb465ef230596b20940eef2b58aa0d99bc0b2#diff-18e4607c02773d0503a9a52f6abcee5c```

Also I deleted unnecessary command from Dockerfile

**Comment by ilyinon** [comment]
Steps which you described currently are implemented.

1.
I haven't got  any checks yet for waiting postgres start, but it works because first command in server container is migration,  if postgres database isn't available then container will restarting.  At the end, when database will have been loaded then server will start.

2.
manage.py migrate is implemeted

3. 
run server with gunicorn is implemented


If you think that step first was implemented incorrectly, could you please open new issue for working with it?
